### ISSUE TITLE
crash on map load

### ISSUE THREAD

**Issue by ihgrant** [brunoais/Transport-fever-event-log#1]
Hiya, I'm getting a crash to desktop using this mod with TPF2 build 35049 for Windows 64-bit (latest, at this point in time). I verified that it happens with only this mod enabled and no others. I've attached an example stdout textfile with the crash details to this issue and would be happy to provide any other details you need.

[e2e6574a-31e7-48fc-b775-248980e643dd_stdout.txt](https://github.com/brunoais/Transport-fever-event-log/files/10305078/e2e6574a-31e7-48fc-b775-248980e643dd_stdout.txt)

**Comment by brunoais** [comment]
@ihgrant I updated (here and in the workshop) and tagged as version 0.1. Try now

**Comment by ihgrant** [comment]
Thanks for the quick response! I updated the mod and now I'm getting a new error after CTD. It looks like this:
```
__CRASHDB_CRASH__ struct lua::LuaException: C:\GitLab-Runner\builds\1BJoMpBZ\0\ug\urban_games\train_fever\src\Lib\lua\State.cpp:451: void __cdecl lua::State::DoBuffer(const char *,int,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &): error: [string "D:/STEAM/steamapps/workshop/content/1066780/2775765248/res/config/game_script/event_log.lua"]:19: module 'lib.brunoais.modules' not found:
	no field package.preload['lib.brunoais.modules']
	no file 'D:/STEAM/steamapps/workshop/content/1066780/2775765248/res/scripts/lib\brunoais\modules.lua'
	no file 'res/scripts/lib\brunoais\modules.lua'

	no file 'D:\STEAM\steamapps\common\Transport Fever 2\lib\brunoais\modules.dll'
	no file 'D:\STEAM\steamapps\common\Transport Fever 2\loadall.dll'
	no file '.\lib\brunoais\modules.dll'
	no file 'D:\STEAM\steamapps\common\Transport Fever 2\lib.dll'
	no file 'D:\STEAM\steamapps\common\Transport Fever 2\loadall.dll'
	no file '.\lib.dll'
stack traceback:
    =[C](-1): ?
    =[C](-1): require
    D:/STEAM/steamapps/workshop/content/1066780/2775765248/res/config/game_script/event_log.lua(19): ?

```

stdout attached as before.
[509811aa-ec6b-4ba3-9361-b858208cfbb4_stdout.txt](https://github.com/brunoais/Transport-fever-event-log/files/10309682/509811aa-ec6b-4ba3-9361-b858208cfbb4_stdout.txt)

**Comment by brunoais** [comment]
Oh! F*** I forgot to upload the lib too! 
Pls wait

**Comment by brunoais** [comment]
@ihgrant I added the library to the steam workshop and marked that mod as requiring the library. Pls check if it's solved now

**Comment by ihgrant** [comment]
@brunoais that fixed it! 💯
